#!/usr/bin/env python3
"""
generate_js.py — Split hsk5_raw.json into 5 group JS files + index.js

Input:  scripts/hsk5_raw.json
Output: src/js/data/hsk/hsk5-a.js  (entries #1–500)
        src/js/data/hsk/hsk5-b.js  (entries #501–1000)
        src/js/data/hsk/hsk5-c.js  (entries #1001–1500)
        src/js/data/hsk/hsk5-d.js  (entries #1501–2000)
        src/js/data/hsk/hsk5-e.js  (entries #2001–9999)
        src/js/data/hsk/index.js

Usage:
    python3 scripts/generate_js.py
    python3 scripts/generate_js.py --input scripts/hsk5_raw.json --out-dir src/js/data/hsk
"""

import json
import os
import argparse

GROUPS = [
    ("a", "A \u2013 G",  1,    500),
    ("b", "G \u2013 M",  501,  1000),
    ("c", "M \u2013 S",  1001, 1500),
    ("d", "S \u2013 X",  1501, 2000),
    ("e", "X \u2013 Z",  2001, 9999),
]

JS_HEADER = "// Auto-generated by scripts/generate_js.py — DO NOT EDIT\n// Source: scripts/hsk5_raw.json\n"


def esc(s):
    """Escape a string for use inside a JS double-quoted string."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def write_group_file(path, var_name, group_title, entries):
    lines = [
        JS_HEADER,
        f"// Group: {group_title} ({len(entries)} words)",
        f"const {var_name} = [",
    ]
    for e in entries:
        cn = esc(e.get("chinese", ""))
        py = esc(e.get("pinyin", ""))
        vi = esc(e.get("vietnamese", ""))
        lines.append(f'  {{ chinese: "{cn}", pinyin: "{py}", vietnamese: "{vi}" }},')
    lines.append("];")
    lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"  Wrote {path} ({len(entries)} entries)")


def write_index_file(path, groups_meta):
    lines = [
        JS_HEADER,
        "// HSK5_DATA — loaded after hsk5-a.js through hsk5-e.js",
        "const HSK5_DATA = {",
        "  groups: [",
    ]
    for gid, gtitle, var_name, count in groups_meta:
        lines.append(f'    {{ id: "{gid}", title: "{gtitle}", words: {var_name} }},  // {count} words')
    lines += [
        "  ]",
        "};",
        "",
    ]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"  Wrote {path}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input",   default="scripts/hsk5_raw.json")
    parser.add_argument("--out-dir", default="src/js/data/hsk")
    args = parser.parse_args()

    if not os.path.exists(args.input):
        print(f"Input not found: {args.input}")
        print("Run ocr_hsk5.py first.")
        return

    with open(args.input, encoding="utf-8") as f:
        data = json.load(f)

    print(f"Loaded {len(data)} entries from {args.input}")

    # Validate
    missing_vi = [e["num"] for e in data if not e.get("vietnamese")]
    missing_cn = [e["num"] for e in data if not e.get("chinese")]
    if missing_cn:
        print(f"[warn] {len(missing_cn)} entries missing chinese field: {missing_cn[:5]}")
    if missing_vi:
        print(f"[warn] {len(missing_vi)} entries missing vietnamese — run ocr_hsk5.py --resume to fill")

    os.makedirs(args.out_dir, exist_ok=True)

    groups_meta = []
    for gid, gtitle, lo, hi in GROUPS:
        chunk = [e for e in data if lo <= e.get("num", 0) <= hi]
        var_name = f"HSK5_{gid.upper()}"
        path = os.path.join(args.out_dir, f"hsk5-{gid}.js")
        write_group_file(path, var_name, gtitle, chunk)
        groups_meta.append((gid, gtitle, var_name, len(chunk)))

    index_path = os.path.join(args.out_dir, "index.js")
    write_index_file(index_path, groups_meta)

    total = sum(g[3] for g in groups_meta)
    print(f"\nDone. {total} words across {len(GROUPS)} groups.")
    print("\nAdd to src/index.html (after js/data/minna/index.js):")
    for gid, _, _, _ in GROUPS:
        print(f'  <script src="js/data/hsk/hsk5-{gid}.js"></script>')
    print('  <script src="js/data/hsk/index.js"></script>')


if __name__ == "__main__":
    main()
